### PR TITLE
fix: generate_packages.py for unified variant metadata

### PR DESCRIPTION
**Pull request by wdconinc**
This PR fixes the failures that have been happening due to https://github.com/spack/spack/pull/44425.

### CODE REVIEW

**Comment by wdconinc** [comment]
FYI @alalazo @alecbcs 

There is [another actions failure](https://github.com/spack/packages.spack.io/actions/runs/10786199183/job/29912697246) that has been here since Sept 10 that I'm still working on resolving...

**Comment by alalazo** [comment]
Thanks @wdconinc !

**Review by alalazo — APPROVED** [review]

**Comment by tgamblin** [comment]
Oops!  Thanks!

**Comment by wdconinc** [comment]
I was wondering how to test this here for changes in spack. Triggering workflows seems a bit much.

**Pull request merged**
